spring:
  datasource:
    url: jdbc:h2:file:./db/pizzeria
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
#    show-sql: true
  h2:
    console:
      enabled: true

application:
  security:
    jwt:
      secret: ${JWT_PASSWORD:cGFzc3dvcmRwYXNzd29yZHBhc3N3b3JkcGFzc3dvcmRwYXNzd29yZHBhc3N3b3Jk}
      expiration: 300000 # 5 minutes